# Generated by Django 4.2.7 on 2023-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaindetails',
            name='chain_logo',
            field=models.ImageField(upload_to='Media/'),
        ),
    ]
