# Generated by Django 4.2.7 on 2023-11-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaindetails',
            old_name='chain',
            new_name='network_name',
        ),
    ]
